language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install numpy jaxlib jax tensorflow tensorflow-datasets --upgrade
  - cd google
  - pip install -e neural-tangents
script:
  - set -e
  - for f in neural-tangents/neural_tangents/tests/*.py; do python $f; done
