language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install tensorflow tensorflow-datasets
  - pip install git+https://www.github.com/google/neural-tangents
script:
  - for f in neural-tangents/neural_tangents/tests/*.py; do python $f; done
