merge_mode: replace
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install numpy jaxlib jax "tensorflow>=2.2.0rc3" tensorflow-datasets --upgrade
  - git clone https://github.com/google/neural-tangents
  - pip install -e neural-tangents
script:
  - for f in neural-tangents/neural_tangents/tests/*.py; do python $f; done
